name: goreleaser

on:
  pull_request:
  push:

    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install AWS CLI
        run: |
          curl -L https://dl.amazonaws.com/aws-cli/AWSCLI-${{ github.event.repository.os }}-amd64-latest.zip > aws-cli.zip
          unzip aws-cli.zip
          sudo mv aws-cli/aws /usr/local/bin/
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Upload released artifacts to S3
        run: |
          cd ${{ github.workspace }}

          aws s3 cp goreleaser/artifacts/*.tar.gz s3://project-and-company-management-cli-utitlity-tracker/releases/${{ env.GITHUB_REF_NAME }} \
            --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} \
            --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}